fuels_list = [
    "None",
    "Coal",
    "Block_of_coal",
    "Enchanted_Bread",
    "Enchanted_Coal",
    "Solar_Panel",
    "Enchanted_Lava_Bucket",
    "Magma_Bucket",
    "Plasma_Bucket",
    "Everburning_Flame",
    "Hamster_Wheel",
    "Foul_Flesh",
    "Tasty_Cheese",
    "Catalyst",
    "Hyper_Catalyst",
    ]

boosts = {
    "None":                     [0],
    "Coal":                     [0.05],
    "Block_of_coal":            [0.05],
    "Enchanted_Bread":          [0.05],
    "Enchanted_Coal":           [0.1],
    "Solar_Panel":              [12.5],
    "Enchanted_Lava_Bucket":    [0.25],
    "Magma_Bucket":             [0.3],
    "Plasma_Bucket":            [0.35],
    "Everburning_Flame":        [0.4],
    "Hamster_Wheel":            [0.5],
    "Foul_Flesh":               [0.9],
    "Tasty_Cheese":             [1],
    "Catalyst":                 [2],
    "Hyper_Catalyst":           [3],
}